import { FirebaseApp } from 'firebase/app';
import { Firestore } from "firebase/firestore";
import { FirebaseStorage } from "@firebase/storage";
import { User, Auth } from 'firebase/auth';
export declare const firebaseConfig: any;
export declare const application: FirebaseApp;
export declare const db: Firestore;
export declare const storage: FirebaseStorage;
export declare const auth: Auth;
export declare const user: User | null;
